### ISSUE TITLE
欢迎多多Issues

### ISSUE THREAD

**Issue by ZakZheng** [ZakZheng/react-native-waterflow-list#1]

**Comment by YuntongLi6543** [comment]
可以留个联系方式吗？yuntong.li43@gmail.com 有些类似UI功能的问题想请教。

**Comment by ZakZheng** [comment]
微信: qq1258645603

发送自 Windows 10 版邮件应用

发件人: Yuntong Li
发送时间: 2020年7月31日 6:22
收件人: ZakZheng/react-native-waterflow-list
抄送: ZakZheng; Author
主题: Re: [ZakZheng/react-native-waterflow-list] 欢迎多多Issues (#1)

可以留个联系方式吗？yuntong.li43@gmail.com 有些类似UI功能的问题想请教。
