### ISSUE TITLE
When call ListEmptyComponent in columnsFlatListProps return blank ?

### ISSUE THREAD

**Issue by ponleukea** [ZakZheng/react-native-waterflow-list#10]
- React Native version "0.60.0"
- react-native-waterflow-list version "1.2.1"

**Comment by ZakZheng** [comment]
[fixed](https://github.com/ZakZheng/react-native-waterflow-list/commit/35880c15bfb844ae54aa61ac4e29b5155c5fcb10)

**Comment by ponleukea** [comment]
Thanks work !
