### ISSUE TITLE
下拉刷新

### ISSUE THREAD

**Issue by langxiaohui123** [ZakZheng/react-native-waterflow-list#12]
请问下拉刷新怎么支持，在源码直接拓展方法吗？

**Comment by ZakZheng** [comment]
看案例里面有下拉刷新实现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月12日(周三) 晚上6:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ZakZheng/react-native-waterflow-list] 下拉刷新 (#12)




 
请问下拉刷新怎么支持，在源码直接拓展方法吗？

**Comment by ZakZheng** [comment]
看案例里面有下拉刷新实现 @langxiaohui123 

```
 <WaterFlow
     ...
     columnsFlatListProps={{
        ListHeaderComponent: () => <View><Text>Hello</Text></View>,
        refreshControl: <RefreshControl
          style={{ zIndex: 10 }}
          refreshing={loading}
          onRefresh={() => {
            WaterFlowRef.current?.clear()
            loadData()
          }}
          tintColor={'gray'}
        />
        ,
        style: { marginHorizontal: 10, },
      }}
    />
```

**Comment by langxiaohui123** [comment]
好的我试下，谢谢回复！！！

**Comment by langxiaohui123** [comment]
你好作者，就是我这边有换个tab导航，然后组件应该自己会缓存下每个tab下的数据的吧？就是我切换tab的时候不会再去刷新接口，但是我添加了上拉刷新方法，请问怎么避免这种每次tab都刷新，或者怎么样tab切换，直接更新tab对应的list

**Comment by langxiaohui123** [comment]
加了下拉刷新和上拉加载，
然后业务现在是动态tab，不确定tab数量有多少，然后瀑布流就是怎样才能缓存每个tab的内容，不可能用缓存去做，太浪费了，但是不这样点击tab如果不刷新街口，瀑布流一直是之前的tab内容，切换就没什么作用了，想请问下有没有什么好的解决方法？

**Comment by ZakZheng** [comment]
@langxiaohui123 不太明白，点击tab会发生什么，是替换当前瀑布流还是切换到另外一个瀑布流

**Comment by langxiaohui123** [comment]
点击tab是需要缓存当前的tab下面的内容的，

**Comment by langxiaohui123** [comment]
因为只有一个瀑布流容器，所以切换tab后，要触发waterflow clear，然后返回刚才点击的tab，里面的内容我想保留之前看过的，不用去重新调用接口，容器的内容是怎样才能保存下来，tab也是一个list数据，就是类似vue的keep-alive

**Comment by ZakZheng** [comment]
> 因为只有一个瀑布流容器，所以切换tab后，要触发waterflow clear，然后返回刚才点击的tab，里面的内容我想保留之前看过的，不用去重新调用接口，容器的内容是怎样才能保存下来，tab也是一个list数据，就是类似vue的keep-alive
可以看看FlatList有没有对应方法，我认为是没有的。现在瀑布流本质上是一个FlatList。

**Comment by ZakZheng** [comment]
> 因为只有一个瀑布流容器，所以切换tab后，要触发waterflow clear，然后返回刚才点击的tab，里面的内容我想保留之前看过的，不用去重新调用接口，容器的内容是怎样才能保存下来，tab也是一个list数据，就是类似vue的keep-alive

应该是不行，只能创建多个瀑布流吧。可以搜索 FlatList 是否有相关实现，现在瀑布流本质也是FlatList实现的
