### ISSUE TITLE
点击返回按钮后再次进来，右边没有渲染，要滑动下才会渲染

### ISSUE THREAD

**Issue by huaisangyu** [ZakZheng/react-native-waterflow-list#13]
"react": "16.13.1"
    "react-native": "0.63.3",
    "react-native-waterflow-list": "^1.2.3",
    "platform":"ios"
点击返回按钮后再次进来，右边没有渲染，要滑动下才会渲染

**Comment by ZakZheng** [comment]
贴个能重现的代码看看，用的 react-navigation 吗 什么版本
@nangongmoyan
