### ISSUE TITLE
大佬 底层改成 sectionList 可行吗？

### ISSUE THREAD

**Issue by yrang** [ZakZheng/react-native-waterflow-list#25]
目前功能啥都OK的，
但是如果需要需要悬浮某些组件到顶部时，就可能需要页面放 2个 一模一样的的组件，通过监听来实现要不要悬浮。

**Comment by ZakZheng** [comment]
@yrang 可以试试scrollview内嵌一个sectionList，如果没问题应该就可以

**Comment by yrang** [comment]
close
