### ISSUE TITLE
Item顺序错位的问题

### ISSUE THREAD

**Issue by footygoodman** [ZakZheng/react-native-waterflow-list#3]
例子中的代码第二次执行itemDataFactory以后列表中的Item顺序会错位。还没有仔细找原因，能给些线索么？谢谢！

**Comment by ZakZheng** [comment]
可以截个图看看吗。最好是给出实现步骤

**Comment by footygoodman** [comment]
> 可以截个图看看吗。最好是给出实现步骤

就是用Example里的代码，每一个Item代码里都给了一个ID，每页加载10条数据。貌似只有在第一页时item的顺序是对的，后面翻页会有item顺序不对的情况，比如第2张图里ID为26的Item会出现在ID19前面，在将数据分配到哪个flatList里时是会考虑高度问题导致的顺序错位么？第一张图是首次加载数据，Item顺序没问题。后面三张图都有类似问题，想请教是什么原因，谢谢！
[http://182.92.89.199/img/1.jpg](url)  [http://182.92.89.199/img/2.jpg](url)  [http://182.92.89.199/img/3.jpg](url)  [http://182.92.89.199/img/4.jpg](url)

**Comment by footygoodman** [comment]
> 可以截个图看看吗。最好是给出实现步骤

就是用Example里的代码，每一个Item代码里都给了一个ID，每页加载10条数据。貌似只有在第一页时item的顺序是对的，后面翻页会有item顺序不对的情况，比如第2张图里ID为26的Item会出现在ID19前面，在将数据分配到哪个flatList里时是会考虑高度问题导致的顺序错位么？第一张图是首次加载数据，Item顺序没问题。后面三张图都有类似问题，想请教是什么原因，谢谢！
[图一](http://182.92.89.199/img/1.jpg) 
[图二](http://182.92.89.199/img/2.jpg)
[图三](http://182.92.89.199/img/3.jpg)
[图四](http://182.92.89.199/img/4.jpg)

**Comment by ZakZheng** [comment]
@footygoodman 发现问题出在哪里了，其实顺序没问题，只是请求状态的loading被重置了，导致上拉加载时重复调用请求。错乱的那些id其实是因为多次请求导致。现已修复

**Comment by footygoodman** [comment]
@ZakZheng 感谢更新！提个小建议，如果您有时间的话能将WaterFlow暴露一个onViewableItemsChanged事件么？当大量图片加载后内存的开销相当可观，暴露onViewableItemsChanged让外界有机会处理不显示的Item，谢谢！

**Comment by footygoodman** [comment]
> @ZakZheng 感谢更新！提个小建议，如果您有时间的话能将WaterFlow暴露一个onViewableItemsChanged事件么？当大量图片加载后内存的开销相当可观，暴露onViewableItemsChanged让外界有机会处理不显示的Item，谢谢！

在columnFlatListProps里加上onViewableItemsChanged就可以了~谢谢您的更新
