### ISSUE TITLE
Item的排列顺序问题

### ISSUE THREAD

**Issue by YuntongLi6543** [ZakZheng/react-native-waterflow-list#4]
列表render出来之后会出现优先排列右边的一列，再排列左边，有的时候左边会有一些空白。
![图片](https://user-images.githubusercontent.com/46054396/88078943-0b40c000-cb4b-11ea-9521-4dbb81942c44.png)

**Comment by ZakZheng** [comment]
@YuntongLi6543 能否提供一下重现代码？

**Comment by YuntongLi6543** [comment]
<WaterFlow
                data={momentData}
                keyForItem={item => item.id}
                numColumns={2}
                columnFlatListProps={{
                    style: {
                        alignItems: 'center'
                    },
                }}
                columnsFlatListProps={{
                    refreshControl:
                        <RefreshControl
                            refreshing={refresh}
                            onRefresh={() => setRefresh(false)}
                            tintColor="#F2F2F2"
                        />,
                    style: {
                        marginHorizontal: 5,
                        marginVertical: 10
                    }
                }}
                renderItem={({ item }) => (
                    <View style={{
                        backgroundColor: 'white',
                        marginBottom: 12,
                        borderRadius: 5,
                        shadowColor: appColors.black,
                        shadowOffset: {
                            width: 0,
                            height: 1,
                        },
                        shadowOpacity: 0.2,
                        shadowRadius: 5
                    }}>
                        <TouchableOpacity>
                            <AutoHeightImage
                                width={0.46 * screenWidth}
                                source={item.image}
                                style={{ borderRadius: 5 }}
                            />

                            <View style={{ margin: 10 }}>
                                <View>
                                    <Text style={{ fontSize: 10 }}>From: {item.user.name} {item.id}</Text>
                                </View>

                                <View style={{ marginTop: 5 }}>
                                    <Text style={{ fontSize: 10, color: appColors.darkGrey }}>{item.time}</Text>
                                </View>

                                <View style={{ marginTop: 5 }}>
                                    <Text style={{ fontSize: 12 }}>{item.title}</Text>
                                </View>
                            </View>
                        </TouchableOpacity>
                    </View>
                )}
            />

**Comment by ZakZheng** [comment]
@YuntongLi6543 或许是由于组件读取不到renderItem高度导致的。可以尝试给图片一个固定高度

**Comment by YuntongLi6543** [comment]
这个固定的高度是我要单独写一个function 判断图片的高度吗

ZakZheng <notifications@github.com>于2020年7月22日 周三20:52写道：

**Comment by ZakZheng** [comment]
可以像Example里的demo那样，给图片一个固定高度，或者用heightForItem函数返回高度

**Comment by ZakZheng** [comment]
@YuntongLi6543 heightForItem已经支持异步了，可以试试

**Comment by YuntongLi6543** [comment]
解决了，只要 heightForItem    @@@返回一个值就可以了，这个值就算不是图片的真实高度也没问题。谢谢作者@ZakZheng。

                heightForItem={() => {
                    return true;
                }}

**Comment by YuntongLi6543** [comment]
感谢解答，插件写的很不错，如果需要英文方面的documentation乐意帮忙做翻译和完善。

ZakZheng <notifications@github.com> 于2020年7月24日周五 上午2:07写道：

**Comment by ZakZheng** [comment]
@YuntongLi6543 刚更新了包，需要更新到1.2.1才有上面方法

**Comment by YuntongLi6543** [comment]
好 我会再看下代码。

刚在代码里试过了我说的返回一个虚假值，返回的顺序是对的，一左一右排序，不知道会不会是巧合。

ZakZheng <notifications@github.com>于2020年7月25日 周六02:51写道：
