### ISSUE TITLE
渲染少量数据问题

### ISSUE THREAD

**Issue by fengmiaorxiaobai** [ZakZheng/react-native-waterflow-list#5]
渲染两条数据时，横向只展示一条。轻轻上拉能展示出另外一条数据。请问大神是什么问题？@ZakZheng

**Comment by ZakZheng** [comment]
能给个重现代码吗？ @fengmiaorxiaobai

**Comment by fengmiaorxiaobai** [comment]
<WaterFlow
              ref={WaterFlowRef}
              data={selfCollectList}
              keyForItem={(item) => item._id}
              numColumns={2}
              onEndReached={this.loadMore}
              columnsFlatListProps={{
                refreshControl: (
                  <RefreshControl
                    refreshing={this.state.refreshing}
                    onRefresh={() => {
                      this.onRefresh();
                    }}
                  />
                ),
                style: {marginHorizontal: 5},
                showsVerticalScrollIndicator: false,
              }}
              renderItem={this._renderItemWaterfall}
              scrollIndicatorInsets={{right: 1}}
            />
_renderItemWaterfall = (item: any) => {
    // console.log(item)

    return item.item ? (
      <SelfCollectItemWaterfall
        item={item}
        index={item.index}
        deleteMessage={this.deleteMessage}
        goSnapWeb={this.goSnapWeb}
      />
    ) : null;
  };
![WechatIMG2](https://user-images.githubusercontent.com/18523923/94510148-a2f81400-0248-11eb-8d89-e65e668df24c.jpeg)
@ZakZheng

**Comment by ZakZheng** [comment]
似乎没办法重现，我使用 react-native-waterflow-list/Example/index.tsx 并将数据数量成2条，并没出现问题  @fengmiaorxiaobai

**Comment by fengmiaorxiaobai** [comment]
第一次渲染的时候能渲染出来，多次重复进入同一页面，就会渲染一条甚至为空。不知道大神那能否复现？ @ZakZheng

**Comment by fengmiaorxiaobai** [comment]
![1602236787812379](https://user-images.githubusercontent.com/18523923/95569271-e8da8680-0a57-11eb-89f9-dcb57adb8301.gif)

**Comment by fengmiaorxiaobai** [comment]
![1602236787812379](https://user-images.githubusercontent.com/18523923/95569332-060f5500-0a58-11eb-8140-7ac1be97bf0d.gif)

**Comment by ZakZheng** [comment]
可惜我将电脑放在公司了，要下周一才能试一下了 @fengmiaorxiaobai

**Comment by fengmiaorxiaobai** [comment]
没事。我的RN版本号是.62。不知道是不是跟版本号有关系。数据超过两条以上都没问题。也看了源码，打断点看渲染也没看出问题。谢谢大神帮忙看一下。 @ZakZheng

**Comment by ZakZheng** [comment]
找出问题了，在ios下会遇到这个问题。
把 FlatList 的 `removeClippedSubviews` 设置成 `false`
例
```
<WaterFlow
  ......
  columnFlatListProps={{
    removeClippedSubviews: false,
   }}
  ......
/>
```
@fengmiaorxiaobai

**Comment by fengmiaorxiaobai** [comment]
@ZakZheng 感谢大神的解答，问题已经解决。但是有个新问题。就是每次进入同一页面顺序排列有问题。异步高度（asyncHeightForItem）也设置了，不起作用。麻烦大神再看一下。🙏
![1602580419202345](https://user-images.githubusercontent.com/18523923/95841681-3c124900-0d78-11eb-930f-3c90f5207122.gif)

**Comment by ZakZheng** [comment]
看看你的写法 
@fengmiaorxiaobai

**Comment by fengmiaorxiaobai** [comment]
<WaterFlow
              ref={WaterFlowRef}
              data={selfCollectList}
              keyForItem={(item) => item._id}
              numColumns={2}
              onEndReached={this.loadMore}
              columnsFlatListProps={{
                refreshControl: (
                  <RefreshControl
                    refreshing={this.state.refreshing}
                    onRefresh={() => {
                      this.onRefresh();
                    }}
                  />
                ),
                style: {
                  marginHorizontal: 5,
                  marginBottom: isIphoneX()
                    ? getWidthOfPt(20)
                    : getWidthOfPt(10),
                },
              }}
              renderItem={this._renderItemWaterfall}
              scrollIndicatorInsets={{right: 1}}
              asyncHeightForItem={async item => {
                // let imageHeight = 0
                // try {
                //   imageHeight = await (new Promise<number>((resolve, reject) => {
                //     // 获取图片链接的真实高度
                //     Image.getSize(item.image_path, (_, _imageHeight) => {
                //       resolve(_imageHeight)
                //     }, reject)
                //   }))
                // } catch (err) {
                //   console.log({ err });
                // }
                // const titleHeight = 100 // 其他地方的高度
                const height = 400
                return height;
              }}
              
            />

**Comment by ZakZheng** [comment]
`asyncHeightForItem` 这玩意需要返回真实的高度，如果没办法获取到，那就不要传这个。

**Comment by fengmiaorxiaobai** [comment]
我现在去掉这个了，基本就是首次渲染没问题。重新再进入，排序就有问题。

**Comment by ZakZheng** [comment]
你试试Example里面的代码，我这边正常 @fengmiaorxiaobai

**Comment by fengmiaorxiaobai** [comment]
好的。感谢 @ZakZheng
