### ISSUE TITLE
tab点击渲染content内的waterfall组件数据局已经更新，但是页面不更新，请问如何修改

### ISSUE THREAD

**Issue by langxiaohui123** [ZakZheng/react-native-waterflow-list#6]
keyForItem={item => item.id } 这个属性

**Comment by ZakZheng** [comment]
是指某一项 item 局部内容更新？
@langxiaohui123

**Comment by langxiaohui123** [comment]
是整个list列表也就是传给WaterFlow的数据改变了，但是页面不更新，因为是tab导航调用的数据，
业务就是导航tab掉接口渲染数据，呈现在waterflow里面

**Comment by ZakZheng** [comment]
重载数据需要在修改前，调用clear方法
clear : 清空渲染列表, 一般用于下拉刷新获取到数据化,清空之前的数据
`  WaterFlowRef.current?.clear() `
@langxiaohui123

**Comment by langxiaohui123** [comment]
好的谢谢回复了，我去试试下，非常感谢！！！

**Comment by SlardarC** [comment]
删除数据某条数据
deleteWithId(id) {
    const filterData = this.listData.filter(item => {
      return item.id !== id;
    });
    this.listData = filterData;
  }
页面刷新后会白屏,没数据展示
需要调用WaterFlowRef.current?.clear()后再删除数据刷新,但是列表会回到顶部,我想停留在删除数据附近

**Comment by SlardarC** [comment]
> 重载数据需要在修改前，调用clear方法
> clear : 清空渲染列表, 一般用于下拉刷新获取到数据化,清空之前的数据
> ` WaterFlowRef.current?.clear()`
> @langxiaohui123

删除数据某条数据
deleteWithId(id) {
const filterData = this.listData.filter(item => {
return item.id !== id;
});
this.listData = filterData;
}
页面刷新后会白屏,没数据展示
需要调用WaterFlowRef.current?.clear()后再删除数据刷新,但是列表会回到顶部,我想停留在删除数据附近

**Comment by ZakZheng** [comment]
@SlardarC 设计的时候没考虑到删除数据的情况，现在只能清空重载。

**Comment by langxiaohui123** [comment]
这个算是解决了吧，用clear，
不过loadmore，加载上拉加载的时候一次触发好多次加载函数，onloadmore，这个有方法吗

**Comment by ZakZheng** [comment]
参考文档的 onEndReached 方法
onEndReached?: () => Promise<any> | any : 上拉加载, 若传入 Promise 对象, 则须等待 Promise 事件回调后方能再次触发此事件. 若其他则不作处理

@langxiaohui123
