### ISSUE TITLE
onScroll bug

### ISSUE THREAD

**Issue by marlti7** [ZakZheng/react-native-waterflow-list#7]
`<FlatList
      data={columns}
      keyExtractor={(columnItem: T) => `item-${columnItem._keyForItem_}`}
      onScroll={props.onEndReached}
      removeClippedSubviews={true}
      {...columnsFlatListProps}`

你这个地方，如果父级给了columnsFlatListProps onScroll 会覆盖前面的onScroll 

建议改成下面这样 传入onScroll 
`<WaterFlow
                        ref={r => this.WaterFlowRef = r }
                        data={hosList}
                        keyForItem={item => item.id}
                        numColumns={2}
                        onEndReached={this._onEndReached}
                        onScroll={this._onScroll}`

修改源码
`<FlatList
      data={columns}
      keyExtractor={(columnItem: T) => `item-${columnItem._keyForItem_}`}
      onScroll={(e: any) => {
        props.onEndReached(e);
        props.onScroll && props.onScroll(e)
      }}`

**Comment by ZakZheng** [comment]
@marlti7 收到，或许可以提个合并？

**Comment by marlti7** [comment]
> @marlti7 收到，或许可以提个合并？

已提
