### ISSUE TITLE
android出现image为空白情况

### ISSUE THREAD

**Issue by jameswu23** [ZakZheng/react-native-waterflow-list#9]
您好，我是多个tab使用瀑布流，但是android 
Tab1 下滑加载出图片，这时候切换到Tab2,下滑加载出图片，如果其中有何Tab1的image url一样，再返回到Tab1，对应相同的item就会出现空白情况，图片不再显示

`<SafeAreaView style={styles.container}>
        <WaterFlow
          style={{ height: '100%' }}
          ref={(e) => (this.WaterFlowRef = e)}
          data={listData}
          numColumns={2}
          keyForItem={(item) => {
            return `${String(item.id)}+${id}`;
          }}
          asyncHeightForItem={async (item) => {
            return this.getHeightForItem(item);
          }}
          extraData={this.state}
          columnFlatListProps={{
            style: { marginHorizontal: scaleSize(5), backgroundColor: global.ui.backgroundColor },
          }}
          columnsFlatListProps={{
            ref: (c) => {
              this.flatList = c;
            },
            onScroll: this._onScroll,
            onEndReached: this.onEndReached,
            onEndReachedThreshold: 0.01,
            ListFooterComponent: this.renderListFooter,
            refreshControl: (
              <RefreshControl
                style={{ zIndex: 10 }}
                refreshing={isRefreshing}
                onRefresh={this.onRefresh}
                tintColor={'gray'}
                title={isRefreshing ? '刷新中...' : '松开刷新'}
              />
            ),
            style: { marginHorizontal: scaleSize(5) },
          }}
          renderItem={({ item, index }) => {
            return this.renderItem(item, index);
          }}
        />
        {this.state.isTop ? <View /> : this._renderToTopView()}
      </SafeAreaView>`
![image](https://user-images.githubusercontent.com/27839804/106106740-f2ac0500-6180-11eb-8f80-8dfca75d77f6.png)

**Comment by jameswu23** [comment]
![image](https://user-images.githubusercontent.com/27839804/106106766-fd669a00-6180-11eb-89e1-f18e15e348bb.png)

**Comment by ZakZheng** [comment]
@jameswu23 
试试用tab切换Example用例，将图片地址改成相同。是否还有相同问题

**Comment by jameswu23** [comment]
> @jameswu23
> 试试用tab切换Example用例，将图片地址改成相同。是否还有相同问题

谢谢，我解决了，我使用了react-native-fast-image 加载图片没问题，我感觉是缓存的问题

**Comment by ZakZheng** [comment]
> > @jameswu23
> > 试试用tab切换Example用例，将图片地址改成相同。是否还有相同问题
> 
> 谢谢，我解决了，我使用了react-native-fast-image 加载图片没问题，我感觉是缓存的问题

😄
